export function downloadProjectAsZip(
  files: Record<string, string>,
  projectName: string
) {
  // Build a simple ZIP-like format using Blob
  // For a real ZIP we'd use JSZip, but we'll create individual file downloads
  // or a combined text file for now

  // Create a combined file with all code
  let combined = `// ${projectName} - Generated by IFTribe.AI\n`;
  combined += `// ${new Date().toISOString()}\n`;
  combined += `// Files: ${Object.keys(files).length}\n\n`;

  for (const [path, content] of Object.entries(files)) {
    combined += `${"=".repeat(60)}\n`;
    combined += `// FILE: ${path}\n`;
    combined += `${"=".repeat(60)}\n\n`;
    combined += content;
    combined += "\n\n";
  }

  const blob = new Blob([combined], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName.replace(/[^a-zA-Z0-9-_]/g, "-")}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadSingleFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
